server:
  port: 9090


spring:
  application:
    name: auth-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://54.169.219.205:8761/eureka}
#
management:
  tracing:
    sampling:
      probability: 1.0
