server:
  port: 8084


spring:
  application:
    name: communication-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://54.169.219.205:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0