
server:
  port: 8088

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://54.169.219.205:8761/eureka}







#server:
#  port: 8088
#
#spring:
#  application:
#    name: CONFIG-SERVER
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
##        bootstrap: true   # Add this line
#        git:
##          uri: https://github.com/sreejith-a-nair/BusVia-cloud-config-server
#          uri: https://github.com/sreejith-a-nair/cloud-configuration-server
#          search-path: src/main/resources/config
#          default-label: master
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
#      native:
#        search-location: "classpath:/config"
#
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://54.169.219.205:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

#
#end














#server:
#  port: 8088
#
#  spring:
#    application:
#      name: CONFIG-SERVER
#    profiles:
#      active: native
#    cloud:
#      config:
#        server:
#          git:
#            uri: https://github.com/sreejith-a-nair/BusVia-cloud-config-server
#            search-path: src/main/resources/config
#            default-label: master
#            timeout: 5
#            clone-on-start: true
#            force-pull: true
#          native:
#            search-location: "classpath:/config"




#latest
#          uri: https://github.com/sreejith-a-nair/BusVia-cloud-config-server
#          uri: https://github.com/sreejith-a-nair/cloud-configuration-server





#--previous ---
#spring:
#  application:
#    name: CONFIG-SERVER
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/sreejith-a-nair/cloud-configuration-server
#
#server:
#  port: 9092
#
#  application:
#    name: CLOUD-CONFIG-SERVER
#eureka:
#   client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/

#      old---end---
#  instance:
#    hostname: localhost



#spring :
#  application :
#    name : CONFIG-SERVER
#  cloud:
#      config:
#        server:
#          git:
#           uri : https://github.com/sreejith-a-nair/cloud-configuration-server
#
#
#server :
#  port: 9092
#

#    instance:
#        hostname: localhost